
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: test-db
    ports: 
      - 3306:3306